# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5bff525da91f92a18d69bde92f26ca11e5732859fa4ab8e6f9938b26984de5ad58432ea066928e6435bb35bb24dc6149282555dd7c6390182a43674c11d8444f

test:
  secret_key_base: ad0aaac016809a32554739583e3ed202e341116c9aff25f7598d9019ce9c1f7bbb28fbec1358e49ccb6d86e5023fef6af34edaa09967ba551be251f6d028bc1f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
